version: '3'
services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DATABASE
        - DATABASE_ROOT
        - DATABASE_ROOT_PASSWORD
        - DATABASE_USER
        - DATABASE_USER_PASSWORD
    env_file:
      - .env
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart:
      always

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - DATABASE
        - DATABASE_USER
        - DATABASE_USER_PASSWORD
        - DATABASE_HOST
        - WORDPRESS_TITLE
        - WORDPRESS_ADMIN_USER
        - WORDPRESS_ADMIN_PASSWORD
        - WORDPRESS_ADMIN_EMAIL
        - WORDPRESS_USER_USER
        - WORDPRESS_USER_PASSWORD
        - WORDPRESS_USER_EMAIL
        - DOMAIN
    env_file:
      - .env
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    restart:
      always

  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN
    env_file:
      - .env
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    restart:
      always

networks:
  inception:
    driver: bridge
    name: inception

volumes:
  mariadb:
    name: volume-mariadb
    driver_opts:
      o: bind
      type: none
      device: /home/mydomain.42.fr/data/mariadb
  wordpress:
    name: volume-wordpress
    driver_opts:
      o: bind
      type: none
      device: /home/mydomain.42.fr/data/wordpress
